In [277]:
f = open('sentences.txt', 'r')
import re
import numpy as np
from collections import Counter

In [52]:
data_list = f.readlines()

In [213]:
f = open('sentences.txt', 'r')
data_list_1=f.read()

In [82]:
data_list_lower=[str.lower() for str in data_list]


In [260]:
data_list_lower

['in comparison to dogs, cats have not undergone major changes during the domestication process.\n',
 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n',
 'a common interactive use of cat for a single file is to output the content of a file to standard output.\n',
 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n',
 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n',
 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n',
 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n',
 'however, if the output is piped or redirected, cat is unnecessary.\n',
 'cat with one named file is safer whe

In [259]:
data_list_lower_1=[re.split('[^a-z]', str) for str in data_list_lower]
data_list_lower_1

[['in',
  'comparison',
  'to',
  'dogs',
  '',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process',
  '',
  ''],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  '',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  '',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes',
  '',
  ''],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output',
  '',
  ''],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  '',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals',
  '',
  ''],
 ['in',
  'one',
  '',
  'people',
  'deliberately',

In [261]:
for i in data_list_lower_1:
    for j in i:
        if j == '': i.remove(j)
data_list_lower_1

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process',
  ''],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes',
  ''],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output',
  ''],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals',
  ''],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'o

In [314]:
s=0
k=0
text_dict=dict()

for i in data_list_lower_1:
    for j in i:
        if (text_dict.get(j,-1) == -1) & (j != ''):
            text_dict[j]=s
        s=s+1
text_dict

{'in': 0,
 'comparison': 1,
 'to': 2,
 'dogs': 3,
 'cats': 4,
 'have': 5,
 'not': 6,
 'undergone': 7,
 'major': 8,
 'changes': 9,
 'during': 10,
 'the': 11,
 'domestication': 12,
 'process': 13,
 'as': 15,
 'cat': 16,
 'simply': 17,
 'catenates': 18,
 'streams': 19,
 'of': 20,
 'bytes': 21,
 'it': 22,
 'can': 23,
 'be': 24,
 'also': 25,
 'used': 26,
 'concatenate': 28,
 'binary': 29,
 'files': 30,
 'where': 31,
 'will': 33,
 'just': 34,
 'sequence': 36,
 'a': 40,
 'common': 41,
 'interactive': 42,
 'use': 43,
 'for': 46,
 'single': 48,
 'file': 49,
 'is': 50,
 'output': 52,
 'content': 54,
 'standard': 59,
 'hear': 64,
 'sounds': 65,
 'too': 66,
 'faint': 67,
 'or': 68,
 'high': 70,
 'frequency': 72,
 'human': 74,
 'ears': 75,
 'such': 76,
 'those': 78,
 'made': 79,
 'by': 80,
 'mice': 81,
 'and': 82,
 'other': 83,
 'small': 84,
 'animals': 85,
 'one': 88,
 'people': 89,
 'deliberately': 90,
 'tamed': 91,
 'artificial': 97,
 'selection': 98,
 'they': 100,
 'were': 101,
 'useful': 102,


In [323]:
key_list = list(text_dict.keys())
val_list = list(text_dict.values())

In [421]:
a=np.ones((len(data_list_lower_1), len(text_dict)))
s=0
for i in range(0,len(data_list_lower_1)-1):
    for j in range(0,len(val_list)-1):
        
        a[i,j]=data_list_lower_1[i].count(key_list[j])
        s=s+1

[[1. 1. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 2. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [423]:
from scipy.spatial import distance
b=np.empty((len(data_list_lower_1)))
for i in range(1,len(a)):
    b[i-1]=distance.cosine(a[0], a[i],)
print(b)

[0.91010669 0.82786741 0.8509288  0.73647686 0.88731277 0.69617819
 0.86198689 0.85245778 0.86516003 0.78918149 0.83096915 0.79745213
 0.81742581 0.82229534 0.89459074 0.80965325 0.91731018 0.89459074
 0.84188612 0.8012384  0.75698741 1.        ]


In [438]:
b_sort=np.sort(b)
i, = np.where(np.isclose(b, b_sort[0])|np.isclose(b, b_sort[1]) )

In [445]:
i.tofile('otv.txt',' ')